Proyecto/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicioapp.urls')),
    path('',include('tiendaapp.urls')),
    path('',include('carroapp.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('usuariosapp.urls')),

]

carroapp/urls.py
from django.urls import path
from . import views

app_name= "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/",views.Agregar_producto, name="add"),
    path("eliminar/<int:producto_id>/",views.Eliminar_producto, name="remove"),
    path("restar/<int:producto_id>/",views.Restar_producto, name="delete"),
    path("limpiar/",views.limpiar_carro, name="limpiar"),
] 

inicioapp/urls.py
from django.urls import path
from inicioapp import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    
    path('',views.inicio, name= 'index'),
    path('contacto/',views.contacto,name= 'contacto'),
]
urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

loginapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView,logout_then_login,
from django.views.generic.base import View
from inicioapp import views


urlpatterns = [
    path('login/', name='login'),
    path('logout/',name='logout'),
    
    
]

tiendaapp/urls.py
from django.urls import path
from inicioapp import views
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('tienda',views.tienda,name='tienda'),
]

usuariosapp/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name= 'USUARIOS'
urlpatterns = [
    path('registro/', views.registrarse, name="registrarse")
]

carroapp/models.py
from django.db import models

# Create your models here.

tiendaapp/models.py
from django.db import models

# Create your models here.
class CateProducto (models.Model):
    nombre= models.CharField(max_length= 50)
    created =models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now_add=True)

    class  Meta:
        
        verbose_name = 'CateProd'
        verbose_name_plural = 'CateProds'

    def __str__(self):
        return self.nombre

class Productos (models.Model):
    nombre_prod=models.CharField(max_length= 50)
    categoria= models.ForeignKey(CateProducto, on_delete= models.CASCADE)
    imagen=models.ImageField(upload_to='compra')
    precio= models.FloatField()
    disponible= models.BooleanField(default=True)
    created =models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now_add=True)

    
    class Meta:
        
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

inicioapp/forms.py
from django import forms
from django.forms import widgets

class ContactoForm (forms.Form):
    nombre=forms.CharField(label='Nombre',required=True)
    email=forms.CharField(label='Email',required=True)
    contenido=forms.CharField( label='Contenido', widget=forms.Textarea)

usuariosapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistroForm(UserCreationForm):
    username = forms.CharField(label='Usuario', widget=forms.TextInput(attrs={'class': 'usuario'}), max_length=150, required=True, help_text='Requerido. 150 caracteres o menos. Letras, dígitos y @ /. / + /- / _ solamente.')

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Al menos 8 caracteres y no pueden ser todos numeros.')

    password2 = forms.CharField(label='Repetir Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Ingrese la misma contraseña que antes, para verificación.')

    first_name = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={'class': 'nombre'}), max_length=30, required=False, help_text='Opcional.')

    last_name = forms.CharField(label='Apellido', widget=forms.TextInput(attrs={'class': 'apellido'}),max_length=30, required=False, help_text='Opcional.')

    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'email'}), max_length=254, required=True, help_text='Se requiere una direccion de email valida.')


class Meta:
    model = User
    fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

carroapp/views.py
from django.shortcuts import render

from .carro import Carro
from tiendaapp.models import Productos
from django.shortcuts import redirect


# Create your views here.
def Agregar_producto(request,producto_id):
    carro=Carro(request)
    producto=Productos.objects.get (id=producto_id)
    carro.add(producto=producto)
    return redirect("tienda")

def Eliminar_producto(request,producto_id):
    carro=Carro(request)
    producto=Productos.objects.get (id=producto_id)
    carro.remove(producto=producto)
    return redirect("tienda")

def Restar_producto(request,producto_id):
    carro=Carro(request)
    producto=Productos.objects.get (id=producto_id)
    carro.delete(producto=producto)
    return redirect("tienda")

def limpiar_carro(request):
    carro=Carro(request)
    carro.vaciar_carro
    return redirect("tienda")

# Create your views here.

inicioapp/views.py
from django.http import request
from django.shortcuts import render
from .forms import ContactoForm

# Create your views here.

def inicio (request):
    return render (request,"inicioapp/index.html" )


def contacto(request):
    form= ContactoForm 
    return render (request,"inicioapp/contacto.html",{ 'formulario': form})

loginapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required




# Create your views here.
@login_required
def login (request):
    return render (request, 'login')
    

tiendaapp/views.py
from django.shortcuts import render
from .models import CateProducto,Productos

# Create your views here.
def tienda (request):
    productos=Productos.objects.all()
    categoria = CateProducto.objects.all()
    #carro = Carro(request)
    
    return render(request,'tiendaapp/tienda.html', {'productos':productos})

usuariosapp/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import *

def registrarse(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login'))
    else:
        form = RegistroForm()
    return render(request, 'registro/registro.html', {'form': form})

inicioapp/templates/inicioapp/contacto.html
{% extends "inicioapp/layout.html" %}
{%load static %}

{% block body %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-5 border bg-dark text-light p-3 mt-3 rounded-3">
            <h2>Informacion de Contacto</h2>
            
                <form action="contacto" class="forms" method="POST">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <td>Nombre:</td>
                            <td>{{formulario.nombre}}</td>
                        </tr>
                        <tr>
                            <td>Email:</td>
                            <td>{{formulario.email}}</td>
                        </tr>
                        <tr>
                            <td>Asunto:</td>
                            <td>{{formulario.contenido}}</td>
                        </tr>

                    </table>
                    
                    
                    
                    <input class="btn btn-info float-end" type="submit" value="Enviar">

                </form>
                
                
            
        </div>
    </div>
</div>


{% endblock %}

inicioapp/templates/inicioapp/index.html
{% extends "inicioapp/layout.html" %}
{%load static %}

{% block body %}
<div class="container-fluid mt-2">

    <div id="carousel1" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#carousel1" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#carousel1" data-bs-slide-to="1"></li>
            <li data-bs-target="#carousel1" data-bs-slide-to="2"></li>
        </ol>
        <!-- diapositivas -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="static/inicioapp/img/especias.jpg" alt="">
                
                <div class="carousel-caption">
                    <h3>título 1</h3>
                    <p>Descripción de la imagen.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="static/inicioapp/img/botes-de-especias.jpg" alt="">
                <div class="carousel-caption">
                    <h3>título 2</h3>
                    <p>Descripción de la imagen.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="static/inicioapp/img/oregano1.jpg" alt="">
                <div class="carousel-caption">
                    <h3>título 3</h3>
                    <p>Descripción de la imagen.</p>
                </div>
            </div>
        </div>
        <!-- botones de desplazamiento a izquierda y derecha -->
        <a class="carousel-control-prev" href="#carousel1" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel1" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>



{% endblock %}

inicioapp/templates/inicioapp/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jaguarete KAA.</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'inicioapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'inicioapp/css/stylo.css'%}">

</head>

<body>


    <header>
        <div class="container-fluid">
            <div class="row justify-content-between">
                <div class="col-4">
                    <h1 class="title">Jaguarete KAA S.A.</h1>
                </div>


                <div class="col-4 text-light d-flex">
                    {% if user.is_authenticated%}
                    <h3>Hola.. {{user.username}}..!!</h3>
                    {%else %}
                    <h3>Bienvenido</h3>
                    {% endif%}
                </div>
            </div>

        </div>



        


        <nav class="nav  navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid flex-nowrap">
                <div class="row mt-3">
                    <div class="col-2  d-flex ">
                        <ul class="nav bg-light">
                            <li class=" ">
                                <h2><a class="navbar-item text-decoration-none text-dark" href="{% url 'index'%}"><img
                                            src="{% static 'inicioapp/img/yaguarete.png'%}" alt="" 
                                            height="24" class="d-inline ">Jaguarete</a></h2>
                            </li>
                        </ul>
                        
                        
                    </div>
                    <div class="col-4 collapse navbar-collapse d-flex " id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active ms-2" aria-current="page" href="#">Nosotros</a>
                            </li>

                            <li class="nav-item">

                                <a class="nav-link active ms-2" href="{% url 'tienda' %}">Tienda</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active ms-2" href="#" id="navbarDropdown" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Categorias
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                                    <li><a class="dropdown-item" href="#">Especias</a></li>

                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>

                                    <li><a class="dropdown-item" href="#">Chimichurris</a></li>

                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>

                                    <li><a class="dropdown-item" href="#">Oregano</a></li>

                                </ul>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link active ms-2" href="{% url 'contacto' %}">Contacto</a>
                            </li>
                        </ul>
                        <li class="nav-item">
                            <form class="d-flex" action="" method="post">{% csrf_token %}
                                <table>
                                    <tr>
                                        <td><input class="form-control " type="search" placeholder="Buscador"
                                                aria-label="Search"></td>
                                        <td><input class="btn btn-success" type="submit" value="Buscar"></td>
                                    </tr>
                                </table>
                            </form>
                        </li>
                        
                    </div>
                    <div class="col-2 ms-3">
                        <ul class="navbar-nav  mb-2 mb-lg-0">
                            <li class="nav-item me-1">
                                <a class="nav-link active" href="{% url 'USUARIOS:registrarse' %}">Registrarse</a>
                            </li>
                            <li class="nav-item ">
                                {% if user.is_authenticated %}

                                <a class="nav-link text-dark"
                                    href="{% url 'logout'%}?next={{request.path}}">Desconectarse</a>


                                {% else %}

                                <a class="nav-link text-dark" href="{% url 'login'%}">Acceder</a>

                                {% endif %}
                            </li>
                        </ul>
                    </div>


                </div>
            </div>
        </nav>
    </header>






    {% block body%}

    {% endblock %}


    <footer class="footer text-faded text-center py-5">
        <div class="container">
            <p class="m-0">
                <a href="#" class="link">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
                <a href="#" class="link">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
                <a href="#" class="link">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </p>
            <p class="m-0 mbt">
                <a href="sample.html" class="link text-decoration-none text-light">Política de privacidad</a> ·
                <a href="sample.html" class="link text-decoration-none text-light">Aviso legal</a> ·
                <a href="sample.html" class="link text-decoration-none text-light">Cookies</a>
            </p>
            <p class="m-0 mbt1">&copy; Jaguarete KAA S.A</p>
        </div>
    </footer>

    <script src="{% static 'inicioapp/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'inicioapp/js/bootstrap.bundle.min.js' %}"
        integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
        crossorigin="anonymous"></script>
    <script src="{% static 'inicioapp/js/popper.min.js' %}"></script>
    <script src="{% static 'inicioapp/js/bootstrap.min.js' %}"></script>

</body>

</html>

tiendaapp/templates/carro/widghet.html
<div class="table border">

    <table class="m-2">
        <thead>
            <tr>
                <td colspan="4"><h3>Carrito de las compras</h3></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Producto</td>
                <td>Cantidad</td>
                <td>Importe</td>
                <td></td>
            </tr>
            {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items  %}
            <tr class="text-center">
                <td>{{value.nombre}}</td>
                <td>{{value.cantidad}}</td>
                <td>$ {{value.precio}}
                    
                </td>
                <td>
                    <a href="{% url 'carro:add' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                    
                    <a href="{% url 'carro:delete' value.producto_id %}" class="btn btn-sm btn-danger">-</a>
                </td>
            </tr>
            
            {% endfor %}
            {% else %}
            <tr>
                <th colspan="3 "><div class="alert alert-danger" role="alert">
                    No hay Productos
                </div> </th>
            </tr>
            {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <td><strong>Total:$ {{importe_total_carro}}</strong> </td>
                <td><a href="{% url 'carro:limpiar' %}" class="btn btn-sm btn-outline-warning">Limpiar</a></td>
            </tr>
        </tfoot>
    </table>
</div>

tiendaapp/templates/tiendaapp/tienda.html
{% extends "inicioapp/layout.html" %}

{% load static %}

{% block body %}

<div class="container-fluid ">
    <div class="row m-3" style="float:right">
        {% include "carro/widghet.html" %}
    </div>
    <div class="row mb-5">

        {% for producto in productos %}
        <div class="col-lg-3 col-md-6 mb-4" data-aos="fade-up">

            <div class="card shadow-sm m-3" style="width: 10rem; height: 300px;">

                <figure class="block-4-image m-1">
                    <a href=""><img src="{{producto.imagen.url}}" class="img-fluid"></a>
                </figure>


                <div class="" style="text-align: center;">
                    <h6>{{producto.nombre_prod}}</h6>
                    <p class="card-text">${{producto.precio}}</p>
                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'carro:add' producto.id %}" class="btn btn-success">Agregar al Carro</a>
                </div>

            </div>
        </div>
        {% endfor%}
    </div>
</div>
</div>












{% endblock %}

usuariosapp/templates/registro/registro.html
{% extends "inicioapp/layout.html" %}
{%load static %}

{% block body %}
<div class="container ">
    <div class="row justify-content-center">
        <div class="col-4 ms-5  bg-dark text-light rounded-3 mt-3">
            <h2>Formularios de Registro</h2>
            
                <form class="form p-3" method="post">
                    {% csrf_token %}
                    {% for campo in form %}
                    
                        <table>
                            <thead>
                                <tr>
                                    <td>{{campo.label_tag}}</td>
                                    
                                </tr>
                                <tr><td aria-placeholder="">{{ campo }}</td></tr>
                            </thead>
                        </table>

                        {% if campo.help_text %}
                        <small style="color: grey">{{ campo.help_text }}</small>
                        {% endif %}


                        {% for error in campo.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                        </p>
                        {% endfor %}
                        <div class="input float-end mb-3">
                            <input class="btn btn-info rounded-pill" type="submit" value= "Confirmar Registro">
                        </div>
                        
                    </form>
                    
                    
                           
                            
                        
                        
                        
            
        </div>
    </div>
</div>

{% endblock %}